AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SafexpressOps Knowledge Base - PDF Processing & Vector Search System

Globals:
  Function:
    Timeout: 900
    MemorySize: 3008
    Runtime: python3.11
    Architectures:
      - x86_64

Parameters:
  OpenAIAPIKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key
  
  WeaviateURL:
    Type: String
    Description: Weaviate Cluster URL (with https://)
  
  WeaviateAPIKey:
    Type: String
    NoEcho: true
    Description: Weaviate API Key
  
  JWTSecretKey:
    Type: String
    NoEcho: true
    Description: JWT Secret Key for authentication
  
  PDFProcessingLayerArn:
    Type: String
    Description: ARN of existing PDF Processing Layer
    Default: ""
  
  AIVectorDBLayerArn:
    Type: String
    Description: ARN of existing AI/VectorDB Layer
    Default: ""
  
  FastAPICoreLayerArn:
    Type: String
    Description: ARN of existing FastAPI Core Layer
    Default: ""
  
  SecurityAuthLayerArn:
    Type: String
    Description: ARN of existing Security/Auth Layer
    Default: ""
  
  PyMuPDFLayerArn:
    Type: String
    Description: ARN of existing PyMuPDF Layer (for image processor)
    Default: ""

Conditions:
  HasPDFLayer: !Not [!Equals [!Ref PDFProcessingLayerArn, ""]]
  HasAILayer: !Not [!Equals [!Ref AIVectorDBLayerArn, ""]]
  HasFastAPILayer: !Not [!Equals [!Ref FastAPICoreLayerArn, ""]]
  HasSecurityLayer: !Not [!Equals [!Ref SecurityAuthLayerArn, ""]]
  HasPyMuPDFLayer: !Not [!Equals [!Ref PyMuPDFLayerArn, ""]]

Resources:
  # ==================== LAMBDA FUNCTIONS ====================
  
  # Main Knowledge Base API Function
  KnowledgeBaseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafexpressOps-KnowledgeBase
      CodeUri: ./
      Handler: lambda_handler.handler
      Description: Knowledge Base API - PDF Processing & Vector Search
      Layers:
        - !If [HasPDFLayer, !Ref PDFProcessingLayerArn, !Ref AWS::NoValue]
        - !If [HasAILayer, !Ref AIVectorDBLayerArn, !Ref AWS::NoValue]
        - !If [HasFastAPILayer, !Ref FastAPICoreLayerArn, !Ref AWS::NoValue]
        - !If [HasSecurityLayer, !Ref SecurityAuthLayerArn, !Ref AWS::NoValue]
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIAPIKey
          WEAVIATE_URL: !Ref WeaviateURL
          WEAVIATE_API_KEY: !Ref WeaviateAPIKey
          JWT_SECRET_KEY: !Ref JWTSecretKey
          IS_LAMBDA: "true"
          DOCUMENTS_TABLE: !Ref DocumentsTable
          CHAT_SESSIONS_TABLE: !Ref ChatSessionsTable
          CHAT_MESSAGES_TABLE: !Ref ChatMessagesTable
          DOCUMENT_VERSIONS_TABLE: !Ref DocumentVersionsTable
          PDF_STORAGE_BUCKET: !Ref PDFStorageBucket
          IMAGE_PROCESSOR_LAMBDA_ARN: !GetAtt ImageProcessorFunction.Arn
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            TimeoutInMillis: 29000
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref PDFStorageBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatSessionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatMessagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentVersionsTable
        - LambdaInvokePolicy:
            FunctionName: !Ref ImageProcessorFunction
    Metadata:
      BuildMethod: python3.11
  
  # Dedicated Image Processor Function (with PyMuPDF)
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SafexpressOps-ImageProcessor
      CodeUri: ./
      Handler: lambda_image_processor.lambda_handler
      Description: Image extraction from PDFs using PyMuPDF
      Timeout: 300
      MemorySize: 2048
      Layers:
        - !If [HasPyMuPDFLayer, !Ref PyMuPDFLayerArn, !Ref AWS::NoValue]
      Environment:
        Variables:
          IS_LAMBDA: "true"
      ReservedConcurrentExecutions: 5  # Limit concurrent executions
    Metadata:
      BuildMethod: python3.11

  # ==================== DYNAMODB TABLES ====================
  
  ChatSessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: safexpress-chat-sessions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: updated_at
          AttributeType: S
      KeySchema:
        - AttributeName: session_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user-updated-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: updated_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: SafexpressOps

  ChatMessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: safexpress-chat-messages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: message_id
          AttributeType: S
        - AttributeName: session_id
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: message_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: session-timestamp-index
          KeySchema:
            - AttributeName: session_id
              KeyType: HASH
            - AttributeName: timestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: SafexpressOps

  DocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: safexpress-documents
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: doc_id
          AttributeType: S
        - AttributeName: file_name
          AttributeType: S
        - AttributeName: content_hash
          AttributeType: S
      KeySchema:
        - AttributeName: doc_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: filename-index
          KeySchema:
            - AttributeName: file_name
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: content-hash-index
          KeySchema:
            - AttributeName: content_hash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: SafexpressOps

  DocumentVersionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: safexpress-document-versions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: version_id
          AttributeType: S
        - AttributeName: doc_id
          AttributeType: S
      KeySchema:
        - AttributeName: version_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: doc-id-index
          KeySchema:
            - AttributeName: doc_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Project
          Value: SafexpressOps

  # ==================== S3 BUCKET ====================
  
  PDFStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub safexpress-pdf-storage-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: SafexpressOps

Outputs:
  KnowledgeBaseAPI:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  
  FunctionArn:
    Description: Main Lambda Function ARN
    Value: !GetAtt KnowledgeBaseFunction.Arn
  
  ImageProcessorArn:
    Description: Image Processor Lambda Function ARN
    Value: !GetAtt ImageProcessorFunction.Arn
  
  PDFBucket:
    Description: S3 Bucket for PDF storage
    Value: !Ref PDFStorageBucket
  
  DocumentsTableName:
    Description: Documents DynamoDB Table
    Value: !Ref DocumentsTable
  
  ChatSessionsTableName:
    Description: Chat Sessions DynamoDB Table
    Value: !Ref ChatSessionsTable
  
  ChatMessagesTableName:
    Description: Chat Messages DynamoDB Table
    Value: !Ref ChatMessagesTable
  
  DocumentVersionsTableName:
    Description: Document Versions DynamoDB Table
    Value: !Ref DocumentVersionsTable