"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2hqyb%pv70yu5gfu4d=c-mke1=(c$xipt$kdy=%!-x)oo0lvnq"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "d1r565u2m90baj.cloudfront.net",  # Backend CloudFront URL
    "safexpressops-alb-366822214.ap-southeast-1.elb.amazonaws.com",
    "54.251.184.14",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api",
    "corsheaders",
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Custom User Model
AUTH_USER_MODEL = "api.CustomUser"
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Client_id = 460375457443-s7g5sm51b3ouhiqtpjpka6np618ubrjb.apps.googleusercontent.com
# Client_secret = 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
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=51),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=3),
}

# CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    "https://d235efx2egjlji.cloudfront.net",  # Frontend CloudFront URL
    "http://safexpressops-frontend.s3-website-ap-southeast-1.amazonaws.com",  # Your S3 URL (legacy)
    "http://54.251.184.14",  # Your current EC2 for testing
    "http://localhost:3000",  # For local development
    "http://localhost:5173",  # Vite dev server
]

CSRF_TRUSTED_ORIGINS = [
    "https://d235efx2egjlji.cloudfront.net",  # Frontend CloudFront URL
    "https://d1r565u2m90baj.cloudfront.net",  # Backend CloudFront URL
    "http://safexpressops-alb-366822214.ap-southeast-1.elb.amazonaws.com",
    "http://54.251.184.14",
]

CORS_ALLOWS_CREDENTIALS = True

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


LOGIN_REDIRECT_URL = "https://d235efx2egjlji.cloudfront.net/login/callback"
LOGOUT_REDIRECT_URL = "https://d235efx2egjlji.cloudfront.net/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "scope": [
            "openid",
            "email",
            "profile",
            "https://www.googleapis.com/auth/gmail.readonly",
            "https://www.googleapis.com/auth/gmail.send",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/calendar.events",
            "https://www.googleapis.com/auth/calendar.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
        ],
        "AUTH_PARAMS": {
            "access_type": "offline",
            "prompt": "consent",
        },
        "OAUTH_PKCE_ENABLED": True,
        "FETCH_USERINFO": True,
    }
}
SOCIALACCOUNT_STORE_TOKENS = True

# AllAuth settings for custom user model
ACCOUNT_USER_MODEL_EMAIL_FIELD = "gmail"
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = "email"

GOOGLE_OAUTH2_CLIENT_ID = (
    "747803539173-ntak8kgdlpncf93q6g955tukmss974tr.apps.googleusercontent.com"
)
GOOGLE_OAUTH2_CLIENT_SECRET = "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"
GOOGLE_OAUTH2_REDIRECT_URI = "postmessage"

MAPPING_AGENT_URL = "http://localhost:8004"
SHEETS_AGENT_URL = "http://localhost:8003"
ABC_AGENT_URL = "http://localhost:8007"
WORKLOAD_AGENT_URL = "http://localhost:8008"
MONITORING_SERVICE_URL = "http://localhost:8009"
